# Generated by Django 4.2.7 on 2023-11-08 20:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Store', '0002_product_created_product_updated'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order_detail',
            new_name='OrderDetail',
        ),
    ]
